feat: 지원서 진행 상태
mash-up-kr/mashup-server pull request #22
Opened 2022-02-05 10:05 UTC by lee-garden

2022-02-08 13:56 UTC, junhaesung requested changes

2022-02-08 13:56 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationController.java
> +    @PutMapping("/{applicationId}/progress")
`progress` 보다는 사용자가 전형 결과를 확인, 거절한다는 의미가 드러나면 좋을거같아요. 
메서드가 `POST` 인 경우에 `resources/{resourceId}/custom-verb` 형태가 어울릴거같고
`PUT` 이면 `resources/{resourceId}` 에 requestBody 를 덮어쓰는 형태가 좋을거같은데 의견 부탁드려요

2022-02-08 13:56 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationProgressResponse.java
> +    @ApiModelProperty(value = "지원서 진행 상태", example = "WAIT_CONFIRM_INTERVIEW")
`example` 수정해주세요

2022-02-08 13:56 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/progress/ApplicationProgress.java
> +    private Application application;
ApplicationProgress 클래스에서 application 을 사용하지 않는거같은데 양방향으로 매핑하는 이유가 있을까요?

2022-02-08 13:56 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/progress/ApplicationProgressRepository.java
> +    Optional<ApplicationProgress> findByApplication_applicationId(Long applicationProgressId);
쿼리와 parameter 가 서로 다른 값을 가리키고있는데 이름 수정해주세요

2022-02-08 13:56 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/progress/ApplicationProgressServiceImpl.java
> +    public ApplicationProgress getByApplicationId(Long applicationId) {
`ApplicationProgress` 를 조회할 필요가 있을까요? 
`ApplicationService` 에서 처리할 수 있을거같은데요
`ApplicationProgressService`, `ApplicationProgressRepository` 클래스도 필요없어보입니다

2022-02-08 13:56 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/progress/ApplicationProgressStatus.java
> +    TBD("미정"),
figma 에는 미검토로 바뀌어있는데 반영 부탁드려요

2022-02-08 13:56 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/facade/application/ApplicationFacadeService.java
> +    Application updateApplicationProgress(Long applicationId, UpdateApplicationProgressRequest updateRequest);
`applicantId` 도 같이 받아서, 내 소유의 지원서에 대한 접근이 맞는지 검사 필요해보입니다

2022-02-08 16:22 UTC, lee-garden commented on mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationController.java
> +    @PutMapping("/{applicationId}/progress")
오호 일단 이거는 application의 progress라는 테이블을 update하는거니까 [PUT]application/{id}/progress 처럼 생각하긴 했는데요
resources/{resourceId}/custom-verb 가 되면 상태 업데이트 할 수 있는게 4개가 있어서 api 4개가 생길것 같은데 안복잡할까요?

requestBody를 덮어쓴다는게 저번에 말씀하신 멱등성에 관련된 이야기 일까요? ApplicationProgressStatus의 메소드로 지원자가 업데이트 할 수 있는 상태에 대해서는 그렇게 하도록 했는데 혹시 요건 아닐까요?

2022-02-08 19:03 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationController.java
> +    @PutMapping("/{applicationId}/progress")
progress 가 테이블이면 resources 가 되지않을까요. 
`applications/{applicationId}/progresses/{progressId}` 형태가 되어야 PUT 으로 덮어쓰기에 적절할거같습니다. 
특정 필드를 덮어쓰는거라면 `PUT applications/{applicationId}/progress` 도 가능할거같긴합니다

2022-02-08 19:06 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/facade/application/ApplicationFacadeService.java
> +    Application updateApplicationProgress(Long applicationId, UpdateApplicationProgressRequest updateRequest);
로그인 추가되기 전에 controller 에서 tester 가져오도록 하는 코드 추가해둔거 있으니, 이걸로 비즈니스 로직은 커버할수있을거에요. 
로그인 완료되면 controller 만 수정하면 됩니다

2022-02-08 19:07 UTC, junhaesung commented
가능하면 테스트코드 추가해주세요. 
테스트코드 추가 어렵다면 어떻게 테스트했는지 공유해주시면 좋을같아요

2022-02-08 19:28 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationController.java
> +    @PutMapping("/{applicationId}/progress")
다른질문인데, `progress` 이름은 그대로 계속 사용하는건가요? 
아니면 바꿀예정인데 아직 반영 안된걸까요?

2022-02-08 19:31 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/result/ApplicationResultStatus.java
> +    TBD("미검토"),
여기는 staff 가 결과 입력하는 부분이라 제가 수정했어요. 
메신저로 말씀드린건 사용자확인여부에 해당하는`ApplicationProgressStatus.TBD("미정")` 이 부분입니다.

2022-02-09 15:51 UTC, lee-garden commented
> 가능하다면 테스트코드 추가해주세요. 테스트코드 추가 어렵다면 어떻게 테스트했는지 공유해주시면 좋을같아요

테스트는 API직접 찔러서 테스트 해봤습니당

2022-02-10 03:46 UTC, junhaesung reviewed
PR 제목도 수정 부탁드려요
squash merge 하면 PR 제목이 커밋으로 남을텐데, 지금제목은 기능을 잘 설명하지 못하는거같아요

2022-02-10 03:46 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/facade/application/ApplicationFacadeServiceImpl.java
> +     * 지원자 진행 상태  업데이트
`지원서 진행 상태` 라는 이름이 기능을 잘 설명하지 못하는거같아요.

2022-02-10 03:46 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/facade/application/ApplicationFacadeServiceImpl.java
> +        //TODO applicant 인증 도입 되면 applicationId, applicantId로 application 조회해서 validation
applicantId, applicationId 둘다 추가되었으니 주석은 필요없는거같습니다.

2022-02-10 03:46 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationController.java
> +            .updateConfirmation(applicantId, applicationId, updateConfirmationRequest);
지원자가 결과 확인 응답하는 행동을 confirm 으로 표현하고있으니 `updateConfirm` 대신 `confirm` 이 더 좋은 이름인거같아요. 
단순 CRUD 에 매핑하는건 setter 제공하는것과 다르지않아서, 업데이트라는 내부 동작이 이름에 드러나기보다는 객체에 메시지를 전달하게끔 표현하는게 객체지향다운 네이밍입니다.

2022-02-10 03:46 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/ui/application/UpdateConfirmationRequest.java
> +    @ApiModelProperty(value = "지원자 확인 여부", example = "INTERVIEW_CONFIRM_ACCEPTED")
지원자 결고확인 응답의 현재 상태는 true, false 로 나타내는 값이 아니어서 여부라는 표현은 적절하지 않네요
```
여부 
1. 그러함과 그러하지 아니함.
```

2022-02-10 03:46 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationServiceImpl.java
> +        if (!application.getApplicant().getApplicantId().equals(applicantId)) {
쿼리 조건에 applicantId 를 넣지 않고 밖에서 따로 검사하는 이유가 있을까요?

2022-02-10 03:46 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/Application.java
> +    void updateApplicantConfirmationStatus(ApplicantConfirmationStatus status) {
이 메서드도 `confirm` 이 내부 구현을 드러내지 않고 메시지를 전달하는 이름인거같습니다

2022-02-10 03:46 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/confirmation/ApplicantConfirmationStatus.java
> +        throw new ConfirmationUpdateInvalidException();
이 라인은 비즈니스 로직이 아니라, 컴파일 에러를 위한 IllegalStateException() 으로 사용하면 좋을거같아요. 
exception 던지는 로직이 필요하다면 해당 case 안에서 처리하는게 좋을거같습니다. 
이 부분을 로직으로 활용하게되면, enum 을 새로 추가하더라도 서버에러가 아닌 `ConfirmationUpdateInvalidException`상황으로 오해하게끔 만들수있어서요

2022-02-10 03:46 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/confirmation/Confirmation.java
> +    public static Confirmation of() {
이펙티브 자바에 따르면, 정적팩터리메서드의 패러미터 개수에 따라서 관용적으로 사용하는 이름이 있는데요. 
parameter 가 없는 경우 of 를 쓰는건 어색한거같아요

![image](https://user-images.githubusercontent.com/4813025/153332603-2ed846ba-dbf9-4880-8f28-b56451c2ad68.png)

2022-02-10 03:46 UTC, junhaesung commented on mashup-api/src/main/java/kr/mashup/branding/ui/application/ApplicationResponse.java
> +    private final ApplicantConfirmationStatus confirmationStatus;
적을데가 없어서 여기 추가합니다
admin 지원서 응답에도 status 추가 필요할거같아요

2022-02-10 14:16 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/ApplicationServiceImpl.java
> +        if (!application.getApplicant().getApplicantId().equals(applicantId)) {
쿼리 조건에 applicantid를 같이 넣고 검사해서 없으면 익셉션 던지면 될까요? 
저는 항상 뭔가 id로만 조회해서 가져와서 안에 있는 값 보고 판단하는게 익숙했어서 일단 이렇게 하긴 했습니다

2022-02-10 14:24 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/application/confirmation/Confirmation.java
> +    public static Confirmation of() {
헛 그런데 파라미터가 0개일때 적당한 네이밍이 여긴 없는거 같은데 혹시 뭐가 좋을까요?!

2022-02-11 20:20 UTC, junhaesung approved these changes

2022-02-11 21:32 UTC, merged