feat: 어드민 role 추가
mash-up-kr/mashup-server pull request #37
Opened 2022-02-12 16:22 UTC by lee-garden

2022-02-12 23:47 UTC, junhaesung requested changes
어떤 내용 구현한건지랑, 어떻게 테스트했는지 공유해주시면 리뷰할 때 도움될 것 같습니다.

2022-02-12 23:47 UTC, junhaesung commented on mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberAssembler.java
> +            signUpRequest.getDescription(),
description 계속 안쓰게되는데 삭제하는건 어떨까요?

2022-02-12 23:47 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/RolePosition.java
> +    LEADER, SUB_LEADER, STAFF
subleader 한단어라서 언더바 필요없을거같다고 전에 코멘트드렸었는데.. 수정안한이유가있을까요?

2022-02-12 23:47 UTC, junhaesung commented on mashup-domain/src/main/resources/application-local.yml
> +      ddl-auto: create
`create` 로 쓰려는 이유가 있을까요? 
의도치않게 데이터 다 날아가는거 방지하기 위해서 update 로 쓰기로 저번에 수정한거같은데요

2022-02-12 23:47 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/AdminMemberRole.java
> +public class AdminMemberRole {
1:1 관계인데 다른 테이블로 분리한 이유가 있을까요?

2022-02-12 23:47 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/AdminMemberRole.java
> +    private RoleGroup roleGroup;
`RoleGroup`, `RolePosition` 은 우리말로는 어떤 단어로 읽으면 될까요?

2022-02-12 23:47 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/AdminMemberRole.java
> +public class AdminMemberRole {
확장성을 고려한다면, group, position 마다 별개로 m:n 매핑 테이블이 필요하고,
그렇지 않다면 그냥 adminMember 안에 넣으면 될거같아서요.
설계하신 의도가 궁금해서 질문드립니다

2022-02-12 23:47 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/RoleGroup.java
> +    MASH_UP, BRANDING, SPRING, NODE, WEB, DESIGN, ANDROID, IOS
MASH_UP 원래 한단어라서 MASHUP 으로 써도될거같아요. `IOS` 대신 `iOS` 로 쓰는건 어떨까요?

2022-02-13 03:23 UTC, lee-garden commented on mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/AdminMemberAssembler.java
> +            signUpRequest.getDescription(),
그러네용 삭제하겠습니다

2022-02-13 03:25 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/RolePosition.java
> +    LEADER, SUB_LEADER, STAFF
아 이거.. 기존에 피그마에서 SUBLEADER랑 SUB LEADER랑 둘 다 사용되고 있다가 SUB LEADER로 통일되어서 그거 보구 띄워야 되나 해서 또 저렇게 적었었네요 붙이겠습니다

2022-02-13 03:26 UTC, lee-garden commented on mashup-domain/src/main/resources/application-local.yml
> +      ddl-auto: create
이거 테이블 생성 잘 안되서 테스트 하려고 바꿨었는데 깜빡했네요 🙇‍♂️

2022-02-13 03:29 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/AdminMemberRole.java
> +    private RoleGroup roleGroup;
역할 그룹 ...? 
원래는 group, position 으로 쓰려다가 뭔가 다른 의미로 보일수 있을것 같아서 role을 붙였네요

2022-02-13 03:46 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/AdminMemberRole.java
> +public class AdminMemberRole {
음 group과 position이 쌍을 이루어서 역할이라는 어떤 개념을 나타낸다고 생각해서 저렇게 분리 했던것 같습니다

2022-02-13 04:25 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/RolePosition.java
> +    LEADER, SUB_LEADER, STAFF
이거 붙이면 노란줄 뜨긴 하는데 붙일까유?

2022-02-13 04:27 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/role/RoleGroup.java
> +    MASH_UP, BRANDING, SPRING, NODE, WEB, DESIGN, ANDROID, IOS
뭔가 enum은 항상 대문자로만 써왔던것같은데 안 어색할까요? iOS . . .일단 바꿔봤습니다

2022-02-13 09:04 UTC, junhaesung commented on mashup-admin/src/main/java/kr/mashup/branding/ui/adminmember/SignUpRequest.java
> +    private Position position;
도메인 모델로 쓰고있는데, 내부 구현을 dto 까지 공개하면 별로 좋지 않은거같습니다.. 
우리가 enum 바꾸면 회원가입 관련된 외부 모듈까지 다 영향이가서요.
회원가입은 배치로 바꾸기로 한거니까 일단 수정은 안하셔도될거같습니다

2022-02-13 09:04 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/Position.java
> +    IOS_LEADER(Team.iOS),
Team 에서 iOS 로 쓴다면 iOS_LEADER 등으로 변경되면 좋을거같아요

2022-02-13 09:04 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/Position.java
> +    IOS_LEADER(Team.iOS),
만약 iOS 로 써서 warning 나온다면 SupressWarning 어노테이션 추가해주세요.

2022-02-13 09:25 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/Position.java
> +    public enum Team {
음 .. 만약 권한검사 한다면 일단 하드코딩 분기처리 해서 권한 검사 해야 할것 같네요

2022-02-13 09:26 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/Position.java
> +    public enum Team {
`하드코딩 분기처리` 가 뭔지 잘 이해 못했어요. 
권한 검사하는 코드 들어갈 때 한번 설명부탁드려요

2022-02-13 09:43 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/adminmember/Position.java
> +    public enum Team {
아하 team 테이블의 name 과 Position.Team을 직접 검사한다는의미였습니다

2022-02-13 09:55 UTC, junhaesung approved these changes

2022-02-13 10:35 UTC, merged