Feature/sms
mash-up-kr/mashup-server pull request #7
Opened 2022-01-26 15:56 UTC by lee-garden

2022-01-26 16:07 UTC, lee-garden commented
re build

2022-01-26 16:08 UTC, lee-garden commented
rebuild

2022-01-31 07:17 UTC, junhaesung requested changes

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/sms/ToastKeyUtil.java
> +public class ToastKeyUtil {
ToastKeyUtil 이라는 클래스도 toast 라는 벤더의존적인 기능이라서 domain.sms 에 두기는 적절하지 않은거같습니다
Toast 를 빼거나 위치를 옮기거나 해야할거같아요

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/sms/ToastResponseStatus.java
> +public enum ToastResponseStatus {
Toast 관련된 코드 모두 domain 패키지에서 옮겨주세요

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/sms/ToastSmsServiceImpl.java
> +    private HttpHeaders buildHeader() {
헤더 추가하는 등의 공통 작업은 toastRestTemplate 등에서 인터셉터로 처리해도될거같습니다.
이건 그냥 의견이니 반영안해주셔도되어요

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/sms/ToastSmsServiceImpl.java
> +                "01097944578",
보낸 사람 핸드폰번호라고 상수나 변수로 빼놓는게 좋을거같아요

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/util/ProfileUtil.java
> +        return  System.getProperty("spring.profiles.active");
application context 통해서 받아오는게 더 좋지 않을까요?
스프링에 관련 기능 있을거같아요

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/resources/application.yml
> +toast:
toast.sms 보다는 sms.toast 가 좋을거같습니다
어플리케이션 입장에서 관심가는부분은 sms 설정이므로 먼저 나오는게 적절해보이고, sms 안에 여러 벤더들이 사용될 수도 있는 구조가 좋을거같아요

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/resources/application.yml
> +      ddl-auto: create
update 대신 create 로 사용하시는 이유가 있을까요?
`ddl-auto: create` 이면 기존 데이터 다 삭제하고 스키마 새로 만들지않나요? 
local 설정이긴한데, 모두에게 반영되는 내용이라서 조금 위험해보입니다

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/resources/application.yml
> +  datasource:
profile local 이면 devtools 에서 기본설정 넣어주고 있는데, 동일한 값들이 중복으로 추가된거같아요. 
아래 내용 제외하면 중복인거같은데, 이미 반영된 설정을 추가로 써주는게 별로 보기 좋지 않은거같아서요
위에 `@Repository` 어노테이션에 언급한 이유와 비슷한데.. 의견 부탁드립니다

```
console.enabled: 'true'
url: jdbc:h2:~/test;
format_sql: 'true'
show_sql: 'true'
ddl-auto: ...
```

2022-01-31 07:17 UTC, junhaesung commented on mashup-admin/src/main/java/kr/mashup/branding/facade/SmsFacadeService.java
> +            throw new ToastException();
외부 사용자가 ToastException 이라고 구분해서 받을 필요는 없을거같습니다. 
SmsSendFailException 등의 exception 에서, 외부 문자 서비스에서 실패했다는 정도만 알려주어도될거같아요

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/sms/SmsRequest.java
> +    @Column(name = "status")
필드 이름이 status 라서, `@Column` 어노테이션 없이도 동일하게 동작할거같아요

2022-01-31 07:17 UTC, junhaesung commented on mashup-domain/src/main/java/kr/mashup/branding/domain/sms/SmsRequest.java
> +    private SmsRequest(SmsRequestGroup smsRequestGroup, String toastKey, Long userId, String username, String phoneNumber) {
빌더를 사용한다면, 필수 필드가 설정되지 않았을 때 기본값 혹은 validation 에서 예외 던지는 로직이 필요할거같아요. 
작성한사람의 의도는 5개 다 채우는거였지만, 실제 코드는 toastKey 등 1개만 채우고 build() 호출해도 동작하므로 작성자 의도랑 다르게 동작할거같아서요. 
이렇게 validation 없이 builder 사용하면 public setter 를 두는거랑 별다른 차이가 없다고 보여서, 빌더 대신 정적 팩터리 메서드를 사용하는것도 대안이 될 수 있을거같습니다.

2022-01-31 07:17 UTC, junhaesung commented on mashup-admin/src/main/java/kr/mashup/branding/ui/sms/SmsApiController.java
> +    @PostMapping("/request-group/{requestGroupId}/refresh")
아직 구현되지 않은 API 라면 endpoint 를 노출시키지 않거나, 성공응답 대신 아직 완성안되었다는 exception 만들어서 던지면 좋을거같아요
지금은 성공 응답 던지고있어서, 혹시 다른팀에서 호출했을 때 헷갈릴수있을거같습니다.

2022-01-31 08:02 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/sms/SmsRequestGroupServiceImpl.java
> +    public SmsRequestGroup createAndSave(SmsRequestGroupVo smsRequestGroupVo) {
이부분이 중간에 바뀌어서 그런데 

지금 플로우가 이렇게 돼요
1. SmsRequestGroup을 만든다.
2. SmsRequest 집합을 만든다.
3. Toast 문자 발송을 한다.
4. 문자발송의 결과로 SmsRequest의 상태 업데이트를 한다.

그런데 원래는 Group만 만들고 Toast문자 발송 후에 문자 발송 결과를 가지고 SmsRequest를 만들려고 했어요
문자 발송 모두 실패하면(Toast 에러등의 이유) Group만 만들고 SmsRequest를 만들지 않으려고..
이유는 우선 요청을 하면 Group이 만들어 지긴 하는데 에러 응답이 떨어지면 해당 팝업에서 이탈하지 않고 또 요청을 누르면 Group이 두개 생기고,, 결과를 보면 SmsRequestGroupList를 보면 똑같은 타겟의 문자 그룹이 2개 (하나는 성공, 하나는 실패) 생기게 돼요

이 때 실패한 group에 대해서는 실패한 유저 대상 재발송 같은 기능이 있을 텐데 SmsRequestGroup이 실패인 상태로 남아있는게 있으면 부주의로 인해 문자가 두 번 발송되는 일이 있을것 같아서요. 이부분 생각해서 SmsRequest를 늦게 만들려고 했습니다.
사실 처음 의도는 이랬는데 Toast 문서만으론 확인 불가능한게 있어서 지금 로직으로 바뀌긴 했습니다. 지금은 라이프사이클이 같아보이긴 하는데 달라질 여지도 있을것 같고 사실 원래 의도는 그런거였어서 따로 만들어두긴 했습니다

원래 의도는
1. SmsRequestGroup을 만든다.
2. 문자 발송을 한다.
3. 문자 발송의 결과로 SmsRequest를 만들거나 만들지 않는다

2022-01-31 08:13 UTC, lee-garden commented on mashup-admin/src/main/java/kr/mashup/branding/facade/SmsFacadeService.java
> +            throw new ToastException();
이거는 일단 에러응답 어떻게 처리할건지 결정되면 수정 할게요
외부 사용자가 받을 필요는 없는데 어떤 단계에서 실패한건지 저희가 알면 좋을것 같아서 넣었습니당

2022-01-31 08:18 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/util/ProfileUtil.java
> +        return  System.getProperty("spring.profiles.active");
스프링에도 있긴한데 그럼 주입 받아서 써야 해서 필드 하나 더 늘어나는것보다 요렇게 쓰는게 깔끔할것같아서 이렇게 하긴 했습니다

2022-01-31 08:21 UTC, lee-garden commented on mashup-domain/src/main/java/kr/mashup/branding/domain/sms/ToastSmsServiceImpl.java
> +                "01097944578",
저거는 나중에 스태프 번호를 넣어줄건데 일단 임의로 넣어놨습니당

2022-01-31 15:19 UTC, merged